/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: 'class', // Ativar dark mode via classe
  content: [
    './pages/**/*.{js,ts,jsx,tsx,mdx}',
    './components/**/*.{js,ts,jsx,tsx,mdx}',
    './app/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    extend: {
      colors: {
        primary: '#2563eb',
        secondary: '#10b981',
      },
      fontFamily: {
        sans: ['var(--font-inter)', 'Inter', 'system-ui', '-apple-system', 'BlinkMacSystemFont', 'Segoe UI', 'Roboto', 'sans-serif'],
      },
      keyframes: {
        shimmer: {
          '0%': { transform: 'translateX(-100%)' },
          '100%': { transform: 'translateX(100%)' },
        },
        neonGlow: {
          '0%, 100%': { 
            textShadow: '0 0 10px rgba(59, 130, 246, 0.8), 0 0 20px rgba(59, 130, 246, 0.6), 0 0 30px rgba(59, 130, 246, 0.4), 0 0 40px rgba(59, 130, 246, 0.3)' 
          },
          '50%': { 
            textShadow: '0 0 20px rgba(59, 130, 246, 1), 0 0 30px rgba(59, 130, 246, 0.8), 0 0 40px rgba(59, 130, 246, 0.6), 0 0 50px rgba(59, 130, 246, 0.4), 0 0 60px rgba(59, 130, 246, 0.3)' 
          },
        },
        beam: {
          '0%': { opacity: '0.2', transform: 'translateY(-100%)' },
          '50%': { opacity: '0.3' },
          '100%': { opacity: '0.2', transform: 'translateY(100vh)' },
        },
        'led-pulse': {
          '0%, 100%': { opacity: '0.7', transform: 'scale(1)' },
          '50%': { opacity: '1', transform: 'scale(1.2)' },
        },
        bounce1: { '0%, 100%': { transform: 'translateY(0) rotate(0deg)' }, '50%': { transform: 'translateY(-20px) rotate(5deg)' } },
        bounce2: { '0%, 100%': { transform: 'translateY(0) rotate(0deg)' }, '50%': { transform: 'translateY(-25px) rotate(-5deg)' } },
        bounce3: { '0%, 100%': { transform: 'translateY(0) rotate(0deg)' }, '50%': { transform: 'translateY(-30px) rotate(3deg)' } },
        bounce4: { '0%, 100%': { transform: 'translateY(0) rotate(0deg)' }, '50%': { transform: 'translateY(-18px) rotate(-3deg)' } },
        bounce5: { '0%, 100%': { transform: 'translateY(0) rotate(0deg)' }, '50%': { transform: 'translateY(-22px) rotate(4deg)' } },
        bounce6: { '0%, 100%': { transform: 'translateY(0) rotate(0deg)' }, '50%': { transform: 'translateY(-28px) rotate(-4deg)' } },
        bounce7: { '0%, 100%': { transform: 'translateY(0) rotate(0deg)' }, '50%': { transform: 'translateY(-24px) rotate(2deg)' } },
        bounce8: { '0%, 100%': { transform: 'translateY(0) rotate(0deg)' }, '50%': { transform: 'translateY(-26px) rotate(-2deg)' } },
        bounce9: { '0%, 100%': { transform: 'translateY(0) rotate(0deg)' }, '50%': { transform: 'translateY(-19px) rotate(6deg)' } },
        bounce10: { '0%, 100%': { transform: 'translateY(0) rotate(0deg)' }, '50%': { transform: 'translateY(-27px) rotate(-6deg)' } },
        bounce11: { '0%, 100%': { transform: 'translateY(0) rotate(0deg)' }, '50%': { transform: 'translateY(-21px) rotate(3deg)' } },
        bounce12: { '0%, 100%': { transform: 'translateY(0) rotate(0deg)' }, '50%': { transform: 'translateY(-23px) rotate(-3deg)' } },
        bounce13: { '0%, 100%': { transform: 'translateY(0) rotate(0deg)' }, '50%': { transform: 'translateY(-25px) rotate(5deg)' } },
        bounce14: { '0%, 100%': { transform: 'translateY(0) rotate(0deg)' }, '50%': { transform: 'translateY(-20px) rotate(-5deg)' } },
        bounce15: { '0%, 100%': { transform: 'translateY(0) rotate(0deg)' }, '50%': { transform: 'translateY(-29px) rotate(4deg)' } },
        bounce16: { '0%, 100%': { transform: 'translateY(0) rotate(0deg)' }, '50%': { transform: 'translateY(-17px) rotate(-4deg)' } },
        bounce17: { '0%, 100%': { transform: 'translateY(0) rotate(0deg)' }, '50%': { transform: 'translateY(-24px) rotate(2deg)' } },
        bounce18: { '0%, 100%': { transform: 'translateY(0) rotate(0deg)' }, '50%': { transform: 'translateY(-26px) rotate(-2deg)' } },
        bounce19: { '0%, 100%': { transform: 'translateY(0) rotate(0deg)' }, '50%': { transform: 'translateY(-22px) rotate(6deg)' } },
        bounce20: { '0%, 100%': { transform: 'translateY(0) rotate(0deg)' }, '50%': { transform: 'translateY(-28px) rotate(-6deg)' } },
        bounce21: { '0%, 100%': { transform: 'translateY(0) rotate(0deg)' }, '50%': { transform: 'translateY(-19px) rotate(3deg)' } },
        bounce22: { '0%, 100%': { transform: 'translateY(0) rotate(0deg)' }, '50%': { transform: 'translateY(-27px) rotate(-3deg)' } },
        bounce23: { '0%, 100%': { transform: 'translateY(0) rotate(0deg)' }, '50%': { transform: 'translateY(-23px) rotate(5deg)' } },
        bounce24: { '0%, 100%': { transform: 'translateY(0) rotate(0deg)' }, '50%': { transform: 'translateY(-25px) rotate(-5deg)' } },
        bounce25: { '0%, 100%': { transform: 'translateY(0) rotate(0deg)' }, '50%': { transform: 'translateY(-21px) rotate(4deg)' } },
        bounce26: { '0%, 100%': { transform: 'translateY(0) rotate(0deg)' }, '50%': { transform: 'translateY(-26px) rotate(-4deg)' } },
        bounce27: { '0%, 100%': { transform: 'translateY(0) rotate(0deg)' }, '50%': { transform: 'translateY(-18px) rotate(2deg)' } },
        bounce28: { '0%, 100%': { transform: 'translateY(0) rotate(0deg)' }, '50%': { transform: 'translateY(-24px) rotate(-2deg)' } },
      },
      animation: {
        shimmer: 'shimmer 2s infinite',
        neonGlow: 'neonGlow 2s ease-in-out infinite',
        beam: 'beam 3s ease-in-out infinite',
        'beam-delayed': 'beam 3s ease-in-out infinite 1s',
        'beam-slow': 'beam 5s ease-in-out infinite',
        'led-pulse': 'led-pulse 2s ease-in-out infinite',
        'led-pulse-delayed': 'led-pulse 2s ease-in-out infinite 1s',
        bounce1: 'bounce1 4s ease-in-out infinite',
        bounce2: 'bounce2 5s ease-in-out infinite 0.2s',
        bounce3: 'bounce3 6s ease-in-out infinite 0.4s',
        bounce4: 'bounce4 4.5s ease-in-out infinite 0.6s',
        bounce5: 'bounce5 5.5s ease-in-out infinite 0.8s',
        bounce6: 'bounce6 4.2s ease-in-out infinite 1s',
        bounce7: 'bounce7 5.8s ease-in-out infinite 1.2s',
        bounce8: 'bounce8 4.8s ease-in-out infinite 1.4s',
        bounce9: 'bounce9 5.2s ease-in-out infinite 1.6s',
        bounce10: 'bounce10 4.3s ease-in-out infinite 1.8s',
        bounce11: 'bounce11 5.6s ease-in-out infinite 2s',
        bounce12: 'bounce12 4.6s ease-in-out infinite 2.2s',
        bounce13: 'bounce13 5.4s ease-in-out infinite 2.4s',
        bounce14: 'bounce14 4.4s ease-in-out infinite 2.6s',
        bounce15: 'bounce15 5.7s ease-in-out infinite 2.8s',
        bounce16: 'bounce16 4.7s ease-in-out infinite 3s',
        bounce17: 'bounce17 5.3s ease-in-out infinite 3.2s',
        bounce18: 'bounce18 4.5s ease-in-out infinite 3.4s',
        bounce19: 'bounce19 5.9s ease-in-out infinite 3.6s',
        bounce20: 'bounce20 4.1s ease-in-out infinite 3.8s',
        bounce21: 'bounce21 5.5s ease-in-out infinite 4s',
        bounce22: 'bounce22 4.9s ease-in-out infinite 4.2s',
        bounce23: 'bounce23 5.1s ease-in-out infinite 4.4s',
        bounce24: 'bounce24 4.3s ease-in-out infinite 4.6s',
        bounce25: 'bounce25 5.8s ease-in-out infinite 4.8s',
        bounce26: 'bounce26 4.6s ease-in-out infinite 5s',
        bounce27: 'bounce27 5.2s ease-in-out infinite 5.2s',
        bounce28: 'bounce28 4.8s ease-in-out infinite 5.4s',
      },
    },
  },
  plugins: [],
}

